### ISSUE TITLE
composer require peal/barcode-generator     - Could not find a matching version 

### ISSUE THREAD

**Issue by zhengfen** [moin786/laravel-barcode-generator#1]
Could not find a matching version of package peal/barcode-generator. Check the package spelling, your version const
  raint and that the package is available in a stability which matches your minimum-stability (dev).

**Comment by moin786** [comment]
@zhengfen sorry for late feedback, I was busy with one of my project, actually it was mistake from my side, the package name is composer require peal/laravel-barcode-generator not  peal/barcode-generator :)
