### ISSUE TITLE
The code exit on generator barcode

### ISSUE THREAD

**Issue by animexxx** [moin786/laravel-barcode-generator#2]
The php code exit when generator a barcode so i can't get it running continue on my project :(

**Comment by moin786** [comment]
Could you please paste exact error message here? Although I have found a bug and I have fixed it up, now barcode package working fine.

**Comment by moin786** [comment]
Hi @animexxx now you can generate multiple barcode you want, I have fixed up the issues, and also I have updated the documentation how to generate multiple file, please see the readme file and please feedback me on your success. :)

Run the command again
composer require peal/laravel-barcode-generator
