### ISSUE TITLE
Barcode Filepath Issue In Your Library

### ISSUE THREAD

**Issue by chirag2324** [moin786/laravel-barcode-generator#7]
![A](https://user-images.githubusercontent.com/55869433/65746416-6f0d7e80-e11c-11e9-829d-b6c34f30f354.png)
![B](https://user-images.githubusercontent.com/55869433/65746421-73399c00-e11c-11e9-83c4-b35d0630093a.png)

Hello There,

In your library, you have to not set the $this->filepath property in renderBarcode() method and expect in createImage() method.

Please check above 2 screenshots for your code and If possible solve as soon as possible.

Thanks,
Chirag Parmar

**Comment by moin786** [comment]
@chirag2324 Fix up at version 1.2.3
